db:
  redis:
    emulate: ${EG_DB_EMULATE:-true}
    host: localhost
    port: 6379
    namespace: EG

cli:
  url: http://localhost:9876

#plugins:
  # express-gateway-plugin-example:
  #   param1: 'param from system.config'

crypto:
  cipherKey: ${EG_CRYPTO_CIPHER_KEY}
  algorithm: aes-256-cbc
  saltRounds: 10
session:
  secret: ${EG_SESSION_SECRET}
  resave: false
  saveUninitialized: false
accessTokens:
  timeToExpiry: 7200000
refreshTokens:
  timeToExpiry: 7200000
authorizationCodes:
  timeToExpiry: 300000
