db:
  redis:
    host: localhost
    port: 6379
    password: null
    db: 0

crypto:
  cipherKey: ${EG_CRYPTO_CIPHER_KEY}
  algorithm: aes-256-cbc
  saltRounds: 10

session:
  secret: ${EG_SESSION_SECRET}
  resave: false
  saveUninitialized: false

accessTokens:
  timeToExpiry: 7200000

refreshTokens:
  timeToExpiry: 7200000

authorizationCodes:
  timeToExpiry: 300000

policies:
  - ai-router
  - ai-cache
