name: Security
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  "security-scan":
    "runs-on": ubuntu-latest
    permissions:
      "security-events": write
      contents: read
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Run Trivy vulnerability scanner"
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan_type: fs
          format: sarif
          output: trivy-results.sarif
      - name: "Upload Trivy scan results to GitHub Security tab"
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: trivy-results.sarif
